// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AlphasColumns holds the columns for the "alpha" table.
	AlphasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "Uuid", Type: field.TypeString},
		{Name: "FirstInsert", Type: field.TypeString, SchemaType: map[string]string{"mysql": "datetime(6)"}},
		{Name: "LastUpdate", Type: field.TypeString, SchemaType: map[string]string{"mysql": "datetime(6)"}},
		{Name: "Animal", Type: field.TypeString},
		{Name: "BigNumber", Type: field.TypeString},
		{Name: "test_field", Type: field.TypeString, Nullable: true},
	}
	// AlphasTable holds the schema information for the "alpha" table.
	AlphasTable = &schema.Table{
		Name:       "alpha",
		Columns:    AlphasColumns,
		PrimaryKey: []*schema.Column{AlphasColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AlphasTable,
	}
)

func init() {
}
