// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/rah-0/margo-test/ent/alpha"
	"github.com/rah-0/margo-test/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alphaFields := schema.Alpha{}.Fields()
	_ = alphaFields
	// alphaDescUUID is the schema descriptor for Uuid field.
	alphaDescUUID := alphaFields[0].Descriptor()
	// alpha.UUIDValidator is a validator for the "Uuid" field. It is called by the builders before save.
	alpha.UUIDValidator = alphaDescUUID.Validators[0].(func(string) error)
	// alphaDescAnimal is the schema descriptor for Animal field.
	alphaDescAnimal := alphaFields[3].Descriptor()
	// alpha.AnimalValidator is a validator for the "Animal" field. It is called by the builders before save.
	alpha.AnimalValidator = alphaDescAnimal.Validators[0].(func(string) error)
}
