package AllTypes

// ---------------------------------------------------------------
// The code in this file is autogenerated, do not modify manually!
// ---------------------------------------------------------------

import (
	"context"
	"database/sql"
	"strings"
	"sync"
)

const (
	FQTN                 = "`template`.`all_types`"
	FieldId              = "id"
	FieldTinySigned      = "tiny_signed"
	FieldTinyUnsigned    = "tiny_unsigned"
	FieldSmallSigned     = "small_signed"
	FieldSmallUnsigned   = "small_unsigned"
	FieldMediumSigned    = "medium_signed"
	FieldMediumUnsigned  = "medium_unsigned"
	FieldIntSigned       = "int_signed"
	FieldIntUnsigned     = "int_unsigned"
	FieldBigSigned       = "big_signed"
	FieldBigUnsigned     = "big_unsigned"
	FieldFloatField      = "float_field"
	FieldDoubleField     = "double_field"
	FieldRealField       = "real_field"
	FieldDecimalField    = "decimal_field"
	FieldDecField        = "dec_field"
	FieldNumericField    = "numeric_field"
	FieldFixedField      = "fixed_field"
	FieldBit1            = "bit1"
	FieldBit8            = "bit8"
	FieldBit64           = "bit64"
	FieldBoolField       = "bool_field"
	FieldBooleanField    = "boolean_field"
	FieldCharField       = "char_field"
	FieldVarcharField    = "varchar_field"
	FieldTextField       = "text_field"
	FieldTinytextField   = "tinytext_field"
	FieldMediumtextField = "mediumtext_field"
	FieldLongtextField   = "longtext_field"
	FieldEnumField       = "enum_field"
	FieldSetField        = "set_field"
	FieldBinaryField     = "binary_field"
	FieldVarbinaryField  = "varbinary_field"
	FieldBlobField       = "blob_field"
	FieldTinyblobField   = "tinyblob_field"
	FieldMediumblobField = "mediumblob_field"
	FieldLongblobField   = "longblob_field"
	FieldDateField       = "date_field"
	FieldTimeField       = "time_field"
	FieldYearField       = "year_field"
	FieldDatetimeField   = "datetime_field"
	FieldTimestampField  = "timestamp_field"
	FieldUuidField       = "uuid_field"
)

var (
	Fields    = []string{FieldId, FieldTinySigned, FieldTinyUnsigned, FieldSmallSigned, FieldSmallUnsigned, FieldMediumSigned, FieldMediumUnsigned, FieldIntSigned, FieldIntUnsigned, FieldBigSigned, FieldBigUnsigned, FieldFloatField, FieldDoubleField, FieldRealField, FieldDecimalField, FieldDecField, FieldNumericField, FieldFixedField, FieldBit1, FieldBit8, FieldBit64, FieldBoolField, FieldBooleanField, FieldCharField, FieldVarcharField, FieldTextField, FieldTinytextField, FieldMediumtextField, FieldLongtextField, FieldEnumField, FieldSetField, FieldBinaryField, FieldVarbinaryField, FieldBlobField, FieldTinyblobField, FieldMediumblobField, FieldLongblobField, FieldDateField, FieldTimeField, FieldYearField, FieldDatetimeField, FieldTimestampField, FieldUuidField}
	db        *sql.DB
	stmtMu    sync.RWMutex
	stmtCache = make(map[string]*sql.Stmt)
)

type Entity struct {
	Id              string `json:",omitempty,omitzero"`
	TinySigned      string `json:",omitempty,omitzero"`
	TinyUnsigned    string `json:",omitempty,omitzero"`
	SmallSigned     string `json:",omitempty,omitzero"`
	SmallUnsigned   string `json:",omitempty,omitzero"`
	MediumSigned    string `json:",omitempty,omitzero"`
	MediumUnsigned  string `json:",omitempty,omitzero"`
	IntSigned       string `json:",omitempty,omitzero"`
	IntUnsigned     string `json:",omitempty,omitzero"`
	BigSigned       string `json:",omitempty,omitzero"`
	BigUnsigned     string `json:",omitempty,omitzero"`
	FloatField      string `json:",omitempty,omitzero"`
	DoubleField     string `json:",omitempty,omitzero"`
	RealField       string `json:",omitempty,omitzero"`
	DecimalField    string `json:",omitempty,omitzero"`
	DecField        string `json:",omitempty,omitzero"`
	NumericField    string `json:",omitempty,omitzero"`
	FixedField      string `json:",omitempty,omitzero"`
	Bit1            string `json:",omitempty,omitzero"`
	Bit8            string `json:",omitempty,omitzero"`
	Bit64           string `json:",omitempty,omitzero"`
	BoolField       string `json:",omitempty,omitzero"`
	BooleanField    string `json:",omitempty,omitzero"`
	CharField       string `json:",omitempty,omitzero"`
	VarcharField    string `json:",omitempty,omitzero"`
	TextField       string `json:",omitempty,omitzero"`
	TinytextField   string `json:",omitempty,omitzero"`
	MediumtextField string `json:",omitempty,omitzero"`
	LongtextField   string `json:",omitempty,omitzero"`
	EnumField       string `json:",omitempty,omitzero"`
	SetField        string `json:",omitempty,omitzero"`
	BinaryField     string `json:",omitempty,omitzero"`
	VarbinaryField  string `json:",omitempty,omitzero"`
	BlobField       string `json:",omitempty,omitzero"`
	TinyblobField   string `json:",omitempty,omitzero"`
	MediumblobField string `json:",omitempty,omitzero"`
	LongblobField   string `json:",omitempty,omitzero"`
	DateField       string `json:",omitempty,omitzero"`
	TimeField       string `json:",omitempty,omitzero"`
	YearField       string `json:",omitempty,omitzero"`
	DatetimeField   string `json:",omitempty,omitzero"`
	TimestampField  string `json:",omitempty,omitzero"`
	UuidField       string `json:",omitempty,omitzero"`
}

func SetDB(x *sql.DB) {
	db = x
}

func (x *Entity) GetFieldValue(field string) any {
	switch field {
	case FieldId:
		return x.Id
	case FieldTinySigned:
		return x.TinySigned
	case FieldTinyUnsigned:
		return x.TinyUnsigned
	case FieldSmallSigned:
		return x.SmallSigned
	case FieldSmallUnsigned:
		return x.SmallUnsigned
	case FieldMediumSigned:
		return x.MediumSigned
	case FieldMediumUnsigned:
		return x.MediumUnsigned
	case FieldIntSigned:
		return x.IntSigned
	case FieldIntUnsigned:
		return x.IntUnsigned
	case FieldBigSigned:
		return x.BigSigned
	case FieldBigUnsigned:
		return x.BigUnsigned
	case FieldFloatField:
		return x.FloatField
	case FieldDoubleField:
		return x.DoubleField
	case FieldRealField:
		return x.RealField
	case FieldDecimalField:
		return x.DecimalField
	case FieldDecField:
		return x.DecField
	case FieldNumericField:
		return x.NumericField
	case FieldFixedField:
		return x.FixedField
	case FieldBit1:
		return x.Bit1
	case FieldBit8:
		return x.Bit8
	case FieldBit64:
		return x.Bit64
	case FieldBoolField:
		return x.BoolField
	case FieldBooleanField:
		return x.BooleanField
	case FieldCharField:
		return x.CharField
	case FieldVarcharField:
		return x.VarcharField
	case FieldTextField:
		return x.TextField
	case FieldTinytextField:
		return x.TinytextField
	case FieldMediumtextField:
		return x.MediumtextField
	case FieldLongtextField:
		return x.LongtextField
	case FieldEnumField:
		return x.EnumField
	case FieldSetField:
		return x.SetField
	case FieldBinaryField:
		return x.BinaryField
	case FieldVarbinaryField:
		return x.VarbinaryField
	case FieldBlobField:
		return x.BlobField
	case FieldTinyblobField:
		return x.TinyblobField
	case FieldMediumblobField:
		return x.MediumblobField
	case FieldLongblobField:
		return x.LongblobField
	case FieldDateField:
		return x.DateField
	case FieldTimeField:
		return x.TimeField
	case FieldYearField:
		return x.YearField
	case FieldDatetimeField:
		return x.DatetimeField
	case FieldTimestampField:
		return x.TimestampField
	case FieldUuidField:
		return x.UuidField
	}
	return nil
}

func (x *Entity) GetFieldsValues(fieldList []string) []any {
	values := make([]any, 0, len(fieldList))
	for _, field := range fieldList {
		values = append(values, x.GetFieldValue(field))
	}
	return values
}

func GetValuePlaceholder(field string) string {
	switch field {
	case FieldId:
		return "?"
	case FieldTinySigned:
		return "?"
	case FieldTinyUnsigned:
		return "?"
	case FieldSmallSigned:
		return "?"
	case FieldSmallUnsigned:
		return "?"
	case FieldMediumSigned:
		return "?"
	case FieldMediumUnsigned:
		return "?"
	case FieldIntSigned:
		return "?"
	case FieldIntUnsigned:
		return "?"
	case FieldBigSigned:
		return "?"
	case FieldBigUnsigned:
		return "?"
	case FieldFloatField:
		return "?"
	case FieldDoubleField:
		return "?"
	case FieldRealField:
		return "?"
	case FieldDecimalField:
		return "?"
	case FieldDecField:
		return "?"
	case FieldNumericField:
		return "?"
	case FieldFixedField:
		return "?"
	case FieldBit1:
		return "?"
	case FieldBit8:
		return "?"
	case FieldBit64:
		return "?"
	case FieldBoolField:
		return "?"
	case FieldBooleanField:
		return "?"
	case FieldCharField:
		return "?"
	case FieldVarcharField:
		return "?"
	case FieldTextField:
		return "?"
	case FieldTinytextField:
		return "?"
	case FieldMediumtextField:
		return "?"
	case FieldLongtextField:
		return "?"
	case FieldEnumField:
		return "?"
	case FieldSetField:
		return "?"
	case FieldBinaryField:
		return "?"
	case FieldVarbinaryField:
		return "?"
	case FieldBlobField:
		return "?"
	case FieldTinyblobField:
		return "?"
	case FieldMediumblobField:
		return "?"
	case FieldLongblobField:
		return "?"
	case FieldDateField:
		return "?"
	case FieldTimeField:
		return "?"
	case FieldYearField:
		return "?"
	case FieldDatetimeField:
		return "?"
	case FieldTimestampField:
		return "?"
	case FieldUuidField:
		return "?"
	}
	return ""
}

func GetValuesPlaceholders(fieldList []string) []string {
	placeholders := make([]string, 0, len(fieldList))
	for _, field := range fieldList {
		placeholders = append(placeholders, GetValuePlaceholder(field))
	}
	return placeholders
}

func GetQualifiedField(field string) string {
	switch field {
	case FieldId:
		return FQTN + ".`" + FieldId + "`"
	case FieldTinySigned:
		return FQTN + ".`" + FieldTinySigned + "`"
	case FieldTinyUnsigned:
		return FQTN + ".`" + FieldTinyUnsigned + "`"
	case FieldSmallSigned:
		return FQTN + ".`" + FieldSmallSigned + "`"
	case FieldSmallUnsigned:
		return FQTN + ".`" + FieldSmallUnsigned + "`"
	case FieldMediumSigned:
		return FQTN + ".`" + FieldMediumSigned + "`"
	case FieldMediumUnsigned:
		return FQTN + ".`" + FieldMediumUnsigned + "`"
	case FieldIntSigned:
		return FQTN + ".`" + FieldIntSigned + "`"
	case FieldIntUnsigned:
		return FQTN + ".`" + FieldIntUnsigned + "`"
	case FieldBigSigned:
		return FQTN + ".`" + FieldBigSigned + "`"
	case FieldBigUnsigned:
		return FQTN + ".`" + FieldBigUnsigned + "`"
	case FieldFloatField:
		return FQTN + ".`" + FieldFloatField + "`"
	case FieldDoubleField:
		return FQTN + ".`" + FieldDoubleField + "`"
	case FieldRealField:
		return FQTN + ".`" + FieldRealField + "`"
	case FieldDecimalField:
		return FQTN + ".`" + FieldDecimalField + "`"
	case FieldDecField:
		return FQTN + ".`" + FieldDecField + "`"
	case FieldNumericField:
		return FQTN + ".`" + FieldNumericField + "`"
	case FieldFixedField:
		return FQTN + ".`" + FieldFixedField + "`"
	case FieldBit1:
		return FQTN + ".`" + FieldBit1 + "`"
	case FieldBit8:
		return FQTN + ".`" + FieldBit8 + "`"
	case FieldBit64:
		return FQTN + ".`" + FieldBit64 + "`"
	case FieldBoolField:
		return FQTN + ".`" + FieldBoolField + "`"
	case FieldBooleanField:
		return FQTN + ".`" + FieldBooleanField + "`"
	case FieldCharField:
		return FQTN + ".`" + FieldCharField + "`"
	case FieldVarcharField:
		return FQTN + ".`" + FieldVarcharField + "`"
	case FieldTextField:
		return FQTN + ".`" + FieldTextField + "`"
	case FieldTinytextField:
		return FQTN + ".`" + FieldTinytextField + "`"
	case FieldMediumtextField:
		return FQTN + ".`" + FieldMediumtextField + "`"
	case FieldLongtextField:
		return FQTN + ".`" + FieldLongtextField + "`"
	case FieldEnumField:
		return FQTN + ".`" + FieldEnumField + "`"
	case FieldSetField:
		return FQTN + ".`" + FieldSetField + "`"
	case FieldBinaryField:
		return FQTN + ".`" + FieldBinaryField + "`"
	case FieldVarbinaryField:
		return FQTN + ".`" + FieldVarbinaryField + "`"
	case FieldBlobField:
		return FQTN + ".`" + FieldBlobField + "`"
	case FieldTinyblobField:
		return FQTN + ".`" + FieldTinyblobField + "`"
	case FieldMediumblobField:
		return FQTN + ".`" + FieldMediumblobField + "`"
	case FieldLongblobField:
		return FQTN + ".`" + FieldLongblobField + "`"
	case FieldDateField:
		return FQTN + ".`" + FieldDateField + "`"
	case FieldTimeField:
		return FQTN + ".`" + FieldTimeField + "`"
	case FieldYearField:
		return FQTN + ".`" + FieldYearField + "`"
	case FieldDatetimeField:
		return FQTN + ".`" + FieldDatetimeField + "`"
	case FieldTimestampField:
		return FQTN + ".`" + FieldTimestampField + "`"
	case FieldUuidField:
		return FQTN + ".`" + FieldUuidField + "`"
	}
	return ""
}

func GetQualifiedFields(fieldList []string) []string {
	fields := make([]string, 0, len(fieldList))
	for _, field := range fieldList {
		fields = append(fields, GetQualifiedField(field))
	}
	return fields
}

func GetQualifiedPlaceholder(field string) string {
	switch field {
	case FieldId:
		return FQTN + ".`" + FieldId + "` = ?"
	case FieldTinySigned:
		return FQTN + ".`" + FieldTinySigned + "` = ?"
	case FieldTinyUnsigned:
		return FQTN + ".`" + FieldTinyUnsigned + "` = ?"
	case FieldSmallSigned:
		return FQTN + ".`" + FieldSmallSigned + "` = ?"
	case FieldSmallUnsigned:
		return FQTN + ".`" + FieldSmallUnsigned + "` = ?"
	case FieldMediumSigned:
		return FQTN + ".`" + FieldMediumSigned + "` = ?"
	case FieldMediumUnsigned:
		return FQTN + ".`" + FieldMediumUnsigned + "` = ?"
	case FieldIntSigned:
		return FQTN + ".`" + FieldIntSigned + "` = ?"
	case FieldIntUnsigned:
		return FQTN + ".`" + FieldIntUnsigned + "` = ?"
	case FieldBigSigned:
		return FQTN + ".`" + FieldBigSigned + "` = ?"
	case FieldBigUnsigned:
		return FQTN + ".`" + FieldBigUnsigned + "` = ?"
	case FieldFloatField:
		return FQTN + ".`" + FieldFloatField + "` = ?"
	case FieldDoubleField:
		return FQTN + ".`" + FieldDoubleField + "` = ?"
	case FieldRealField:
		return FQTN + ".`" + FieldRealField + "` = ?"
	case FieldDecimalField:
		return FQTN + ".`" + FieldDecimalField + "` = ?"
	case FieldDecField:
		return FQTN + ".`" + FieldDecField + "` = ?"
	case FieldNumericField:
		return FQTN + ".`" + FieldNumericField + "` = ?"
	case FieldFixedField:
		return FQTN + ".`" + FieldFixedField + "` = ?"
	case FieldBit1:
		return FQTN + ".`" + FieldBit1 + "` = ?"
	case FieldBit8:
		return FQTN + ".`" + FieldBit8 + "` = ?"
	case FieldBit64:
		return FQTN + ".`" + FieldBit64 + "` = ?"
	case FieldBoolField:
		return FQTN + ".`" + FieldBoolField + "` = ?"
	case FieldBooleanField:
		return FQTN + ".`" + FieldBooleanField + "` = ?"
	case FieldCharField:
		return FQTN + ".`" + FieldCharField + "` = ?"
	case FieldVarcharField:
		return FQTN + ".`" + FieldVarcharField + "` = ?"
	case FieldTextField:
		return FQTN + ".`" + FieldTextField + "` = ?"
	case FieldTinytextField:
		return FQTN + ".`" + FieldTinytextField + "` = ?"
	case FieldMediumtextField:
		return FQTN + ".`" + FieldMediumtextField + "` = ?"
	case FieldLongtextField:
		return FQTN + ".`" + FieldLongtextField + "` = ?"
	case FieldEnumField:
		return FQTN + ".`" + FieldEnumField + "` = ?"
	case FieldSetField:
		return FQTN + ".`" + FieldSetField + "` = ?"
	case FieldBinaryField:
		return FQTN + ".`" + FieldBinaryField + "` = ?"
	case FieldVarbinaryField:
		return FQTN + ".`" + FieldVarbinaryField + "` = ?"
	case FieldBlobField:
		return FQTN + ".`" + FieldBlobField + "` = ?"
	case FieldTinyblobField:
		return FQTN + ".`" + FieldTinyblobField + "` = ?"
	case FieldMediumblobField:
		return FQTN + ".`" + FieldMediumblobField + "` = ?"
	case FieldLongblobField:
		return FQTN + ".`" + FieldLongblobField + "` = ?"
	case FieldDateField:
		return FQTN + ".`" + FieldDateField + "` = ?"
	case FieldTimeField:
		return FQTN + ".`" + FieldTimeField + "` = ?"
	case FieldYearField:
		return FQTN + ".`" + FieldYearField + "` = ?"
	case FieldDatetimeField:
		return FQTN + ".`" + FieldDatetimeField + "` = ?"
	case FieldTimestampField:
		return FQTN + ".`" + FieldTimestampField + "` = ?"
	case FieldUuidField:
		return FQTN + ".`" + FieldUuidField + "` = ?"
	}
	return ""
}

func GetQualifiedPlaceholders(fieldList []string) []string {
	placeholders := make([]string, 0, len(fieldList))
	for _, field := range fieldList {
		placeholders = append(placeholders, GetQualifiedPlaceholder(field))
	}
	return placeholders
}

func getPreparedStmt(query string) (*sql.Stmt, error) {
	stmtMu.RLock()
	if stmt, ok := stmtCache[query]; ok {
		stmtMu.RUnlock()
		return stmt, nil
	}
	stmtMu.RUnlock()

	stmtMu.Lock()
	defer stmtMu.Unlock()
	if stmt, ok := stmtCache[query]; ok {
		return stmt, nil
	}
	stmt, err := db.Prepare(query)
	if err != nil {
		return nil, err
	}
	stmtCache[query] = stmt
	return stmt, nil
}

func scanRow(fields []string, rows *sql.Rows) (*Entity, error) {
	x := &Entity{}
	var (
		ptrId              *string
		ptrTinySigned      *string
		ptrTinyUnsigned    *string
		ptrSmallSigned     *string
		ptrSmallUnsigned   *string
		ptrMediumSigned    *string
		ptrMediumUnsigned  *string
		ptrIntSigned       *string
		ptrIntUnsigned     *string
		ptrBigSigned       *string
		ptrBigUnsigned     *string
		ptrFloatField      *string
		ptrDoubleField     *string
		ptrRealField       *string
		ptrDecimalField    *string
		ptrDecField        *string
		ptrNumericField    *string
		ptrFixedField      *string
		ptrBit1            *string
		ptrBit8            *string
		ptrBit64           *string
		ptrBoolField       *string
		ptrBooleanField    *string
		ptrCharField       *string
		ptrVarcharField    *string
		ptrTextField       *string
		ptrTinytextField   *string
		ptrMediumtextField *string
		ptrLongtextField   *string
		ptrEnumField       *string
		ptrSetField        *string
		ptrBinaryField     *string
		ptrVarbinaryField  *string
		ptrBlobField       *string
		ptrTinyblobField   *string
		ptrMediumblobField *string
		ptrLongblobField   *string
		ptrDateField       *string
		ptrTimeField       *string
		ptrYearField       *string
		ptrDatetimeField   *string
		ptrTimestampField  *string
		ptrUuidField       *string
		scanTargets        []any
	)

	for _, field := range fields {
		switch field {
		case FieldId:
			scanTargets = append(scanTargets, &ptrId)
		case FieldTinySigned:
			scanTargets = append(scanTargets, &ptrTinySigned)
		case FieldTinyUnsigned:
			scanTargets = append(scanTargets, &ptrTinyUnsigned)
		case FieldSmallSigned:
			scanTargets = append(scanTargets, &ptrSmallSigned)
		case FieldSmallUnsigned:
			scanTargets = append(scanTargets, &ptrSmallUnsigned)
		case FieldMediumSigned:
			scanTargets = append(scanTargets, &ptrMediumSigned)
		case FieldMediumUnsigned:
			scanTargets = append(scanTargets, &ptrMediumUnsigned)
		case FieldIntSigned:
			scanTargets = append(scanTargets, &ptrIntSigned)
		case FieldIntUnsigned:
			scanTargets = append(scanTargets, &ptrIntUnsigned)
		case FieldBigSigned:
			scanTargets = append(scanTargets, &ptrBigSigned)
		case FieldBigUnsigned:
			scanTargets = append(scanTargets, &ptrBigUnsigned)
		case FieldFloatField:
			scanTargets = append(scanTargets, &ptrFloatField)
		case FieldDoubleField:
			scanTargets = append(scanTargets, &ptrDoubleField)
		case FieldRealField:
			scanTargets = append(scanTargets, &ptrRealField)
		case FieldDecimalField:
			scanTargets = append(scanTargets, &ptrDecimalField)
		case FieldDecField:
			scanTargets = append(scanTargets, &ptrDecField)
		case FieldNumericField:
			scanTargets = append(scanTargets, &ptrNumericField)
		case FieldFixedField:
			scanTargets = append(scanTargets, &ptrFixedField)
		case FieldBit1:
			scanTargets = append(scanTargets, &ptrBit1)
		case FieldBit8:
			scanTargets = append(scanTargets, &ptrBit8)
		case FieldBit64:
			scanTargets = append(scanTargets, &ptrBit64)
		case FieldBoolField:
			scanTargets = append(scanTargets, &ptrBoolField)
		case FieldBooleanField:
			scanTargets = append(scanTargets, &ptrBooleanField)
		case FieldCharField:
			scanTargets = append(scanTargets, &ptrCharField)
		case FieldVarcharField:
			scanTargets = append(scanTargets, &ptrVarcharField)
		case FieldTextField:
			scanTargets = append(scanTargets, &ptrTextField)
		case FieldTinytextField:
			scanTargets = append(scanTargets, &ptrTinytextField)
		case FieldMediumtextField:
			scanTargets = append(scanTargets, &ptrMediumtextField)
		case FieldLongtextField:
			scanTargets = append(scanTargets, &ptrLongtextField)
		case FieldEnumField:
			scanTargets = append(scanTargets, &ptrEnumField)
		case FieldSetField:
			scanTargets = append(scanTargets, &ptrSetField)
		case FieldBinaryField:
			scanTargets = append(scanTargets, &ptrBinaryField)
		case FieldVarbinaryField:
			scanTargets = append(scanTargets, &ptrVarbinaryField)
		case FieldBlobField:
			scanTargets = append(scanTargets, &ptrBlobField)
		case FieldTinyblobField:
			scanTargets = append(scanTargets, &ptrTinyblobField)
		case FieldMediumblobField:
			scanTargets = append(scanTargets, &ptrMediumblobField)
		case FieldLongblobField:
			scanTargets = append(scanTargets, &ptrLongblobField)
		case FieldDateField:
			scanTargets = append(scanTargets, &ptrDateField)
		case FieldTimeField:
			scanTargets = append(scanTargets, &ptrTimeField)
		case FieldYearField:
			scanTargets = append(scanTargets, &ptrYearField)
		case FieldDatetimeField:
			scanTargets = append(scanTargets, &ptrDatetimeField)
		case FieldTimestampField:
			scanTargets = append(scanTargets, &ptrTimestampField)
		case FieldUuidField:
			scanTargets = append(scanTargets, &ptrUuidField)
		}
	}

	err := rows.Scan(scanTargets...)
	if err != nil {
		return nil, err
	}

	if ptrId != nil {
		x.Id = *ptrId
	} else {
		x.Id = ""
	}
	if ptrTinySigned != nil {
		x.TinySigned = *ptrTinySigned
	} else {
		x.TinySigned = ""
	}
	if ptrTinyUnsigned != nil {
		x.TinyUnsigned = *ptrTinyUnsigned
	} else {
		x.TinyUnsigned = ""
	}
	if ptrSmallSigned != nil {
		x.SmallSigned = *ptrSmallSigned
	} else {
		x.SmallSigned = ""
	}
	if ptrSmallUnsigned != nil {
		x.SmallUnsigned = *ptrSmallUnsigned
	} else {
		x.SmallUnsigned = ""
	}
	if ptrMediumSigned != nil {
		x.MediumSigned = *ptrMediumSigned
	} else {
		x.MediumSigned = ""
	}
	if ptrMediumUnsigned != nil {
		x.MediumUnsigned = *ptrMediumUnsigned
	} else {
		x.MediumUnsigned = ""
	}
	if ptrIntSigned != nil {
		x.IntSigned = *ptrIntSigned
	} else {
		x.IntSigned = ""
	}
	if ptrIntUnsigned != nil {
		x.IntUnsigned = *ptrIntUnsigned
	} else {
		x.IntUnsigned = ""
	}
	if ptrBigSigned != nil {
		x.BigSigned = *ptrBigSigned
	} else {
		x.BigSigned = ""
	}
	if ptrBigUnsigned != nil {
		x.BigUnsigned = *ptrBigUnsigned
	} else {
		x.BigUnsigned = ""
	}
	if ptrFloatField != nil {
		x.FloatField = *ptrFloatField
	} else {
		x.FloatField = ""
	}
	if ptrDoubleField != nil {
		x.DoubleField = *ptrDoubleField
	} else {
		x.DoubleField = ""
	}
	if ptrRealField != nil {
		x.RealField = *ptrRealField
	} else {
		x.RealField = ""
	}
	if ptrDecimalField != nil {
		x.DecimalField = *ptrDecimalField
	} else {
		x.DecimalField = ""
	}
	if ptrDecField != nil {
		x.DecField = *ptrDecField
	} else {
		x.DecField = ""
	}
	if ptrNumericField != nil {
		x.NumericField = *ptrNumericField
	} else {
		x.NumericField = ""
	}
	if ptrFixedField != nil {
		x.FixedField = *ptrFixedField
	} else {
		x.FixedField = ""
	}
	if ptrBit1 != nil {
		x.Bit1 = *ptrBit1
	} else {
		x.Bit1 = ""
	}
	if ptrBit8 != nil {
		x.Bit8 = *ptrBit8
	} else {
		x.Bit8 = ""
	}
	if ptrBit64 != nil {
		x.Bit64 = *ptrBit64
	} else {
		x.Bit64 = ""
	}
	if ptrBoolField != nil {
		x.BoolField = *ptrBoolField
	} else {
		x.BoolField = ""
	}
	if ptrBooleanField != nil {
		x.BooleanField = *ptrBooleanField
	} else {
		x.BooleanField = ""
	}
	if ptrCharField != nil {
		x.CharField = *ptrCharField
	} else {
		x.CharField = ""
	}
	if ptrVarcharField != nil {
		x.VarcharField = *ptrVarcharField
	} else {
		x.VarcharField = ""
	}
	if ptrTextField != nil {
		x.TextField = *ptrTextField
	} else {
		x.TextField = ""
	}
	if ptrTinytextField != nil {
		x.TinytextField = *ptrTinytextField
	} else {
		x.TinytextField = ""
	}
	if ptrMediumtextField != nil {
		x.MediumtextField = *ptrMediumtextField
	} else {
		x.MediumtextField = ""
	}
	if ptrLongtextField != nil {
		x.LongtextField = *ptrLongtextField
	} else {
		x.LongtextField = ""
	}
	if ptrEnumField != nil {
		x.EnumField = *ptrEnumField
	} else {
		x.EnumField = ""
	}
	if ptrSetField != nil {
		x.SetField = *ptrSetField
	} else {
		x.SetField = ""
	}
	if ptrBinaryField != nil {
		x.BinaryField = *ptrBinaryField
	} else {
		x.BinaryField = ""
	}
	if ptrVarbinaryField != nil {
		x.VarbinaryField = *ptrVarbinaryField
	} else {
		x.VarbinaryField = ""
	}
	if ptrBlobField != nil {
		x.BlobField = *ptrBlobField
	} else {
		x.BlobField = ""
	}
	if ptrTinyblobField != nil {
		x.TinyblobField = *ptrTinyblobField
	} else {
		x.TinyblobField = ""
	}
	if ptrMediumblobField != nil {
		x.MediumblobField = *ptrMediumblobField
	} else {
		x.MediumblobField = ""
	}
	if ptrLongblobField != nil {
		x.LongblobField = *ptrLongblobField
	} else {
		x.LongblobField = ""
	}
	if ptrDateField != nil {
		x.DateField = *ptrDateField
	} else {
		x.DateField = ""
	}
	if ptrTimeField != nil {
		x.TimeField = *ptrTimeField
	} else {
		x.TimeField = ""
	}
	if ptrYearField != nil {
		x.YearField = *ptrYearField
	} else {
		x.YearField = ""
	}
	if ptrDatetimeField != nil {
		x.DatetimeField = *ptrDatetimeField
	} else {
		x.DatetimeField = ""
	}
	if ptrTimestampField != nil {
		x.TimestampField = *ptrTimestampField
	} else {
		x.TimestampField = ""
	}
	if ptrUuidField != nil {
		x.UuidField = *ptrUuidField
	} else {
		x.UuidField = ""
	}
	return x, nil
}

func readRows(fields []string, rows *sql.Rows) ([]*Entity, error) {
	defer rows.Close()
	var results []*Entity
	for rows.Next() {
		x, err := scanRow(fields, rows)
		if err != nil {
			return results, err
		}
		results = append(results, x)
	}
	return results, nil
}

func DBTruncate() (sql.Result, error) {
	query := "TRUNCATE TABLE " + FQTN
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	return stmt.Exec()
}

func DBTruncateContext(ctx context.Context) (sql.Result, error) {
	query := "TRUNCATE TABLE " + FQTN
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	return stmt.ExecContext(ctx)
}

func (x *Entity) DBInsert(fieldsToInsert []string) (sql.Result, error) {
	query := "INSERT INTO " + FQTN + " (" + strings.Join(GetQualifiedFields(fieldsToInsert), ", ") + ") VALUES (" + strings.Join(GetValuesPlaceholders(fieldsToInsert), ", ") + ")"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	return stmt.Exec(x.GetFieldsValues(fieldsToInsert)...)
}

func (x *Entity) DBInsertContext(ctx context.Context, fieldsToInsert []string) (sql.Result, error) {
	query := "INSERT INTO " + FQTN + " (" + strings.Join(GetQualifiedFields(fieldsToInsert), ", ") + ") VALUES (" + strings.Join(GetValuesPlaceholders(fieldsToInsert), ", ") + ")"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	return stmt.ExecContext(ctx, x.GetFieldsValues(fieldsToInsert)...)
}

func (x *Entity) DBDeleteWhereAll(fieldsToMatch []string) (sql.Result, error) {
	query := "DELETE FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? AND ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	return stmt.Exec(x.GetFieldsValues(fieldsToMatch)...)
}

func (x *Entity) DBDeleteWhereAllContext(ctx context.Context, fieldsToMatch []string) (sql.Result, error) {
	query := "DELETE FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? AND ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	return stmt.ExecContext(ctx, x.GetFieldsValues(fieldsToMatch)...)
}

func (x *Entity) DBDeleteWhereAny(fieldsToMatch []string) (sql.Result, error) {
	query := "DELETE FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? OR ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	return stmt.Exec(x.GetFieldsValues(fieldsToMatch)...)
}

func (x *Entity) DBDeleteWhereAnyContext(ctx context.Context, fieldsToMatch []string) (sql.Result, error) {
	query := "DELETE FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? OR ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	return stmt.ExecContext(ctx, x.GetFieldsValues(fieldsToMatch)...)
}

func (x *Entity) DBUpdateWhereAll(fieldsToUpdate, fieldsToMatch []string) (sql.Result, error) {
	query := "UPDATE " + FQTN + " SET " + strings.Join(GetQualifiedPlaceholders(fieldsToUpdate), ", ") + " WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? AND ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	values := append(x.GetFieldsValues(fieldsToUpdate), x.GetFieldsValues(fieldsToMatch)...)
	return stmt.Exec(values...)
}

func (x *Entity) DBUpdateWhereAllContext(ctx context.Context, fieldsToUpdate, fieldsToMatch []string) (sql.Result, error) {
	query := "UPDATE " + FQTN + " SET " + strings.Join(GetQualifiedPlaceholders(fieldsToUpdate), ", ") + " WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? AND ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	values := append(x.GetFieldsValues(fieldsToUpdate), x.GetFieldsValues(fieldsToMatch)...)
	return stmt.ExecContext(ctx, values...)
}

func (x *Entity) DBUpdateWhereAny(fieldsToUpdate, fieldsToMatch []string) (sql.Result, error) {
	query := "UPDATE " + FQTN + " SET " + strings.Join(GetQualifiedPlaceholders(fieldsToUpdate), ", ") + " WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? OR ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	values := append(x.GetFieldsValues(fieldsToUpdate), x.GetFieldsValues(fieldsToMatch)...)
	return stmt.Exec(values...)
}

func (x *Entity) DBUpdateWhereAnyContext(ctx context.Context, fieldsToUpdate, fieldsToMatch []string) (sql.Result, error) {
	query := "UPDATE " + FQTN + " SET " + strings.Join(GetQualifiedPlaceholders(fieldsToUpdate), ", ") + " WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? OR ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	values := append(x.GetFieldsValues(fieldsToUpdate), x.GetFieldsValues(fieldsToMatch)...)
	return stmt.ExecContext(ctx, values...)
}

func DBSelectAll() ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.Query()
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func DBSelectAllContext(ctx context.Context) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func DBSelectAllWithFields(fields []string) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(fields), ", ") + " FROM " + FQTN
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.Query()
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(fields, rows)
}

func DBSelectAllWithFieldsContext(ctx context.Context, fields []string) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(fields), ", ") + " FROM " + FQTN
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(fields, rows)
}

func DBSubquerySelectAll(subquery string, args ...any) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN + " " + subquery
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.Query(args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func DBSubquerySelectAllContext(ctx context.Context, subquery string, args ...any) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN + " " + subquery
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func DBSubquerySelectAllWithFields(fields []string, subquery string, args ...any) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(fields), ", ") + " FROM " + FQTN + " " + subquery
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.Query(args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(fields, rows)
}

func DBSubquerySelectAllWithFieldsContext(ctx context.Context, fields []string, subquery string, args ...any) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(fields), ", ") + " FROM " + FQTN + " " + subquery
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(fields, rows)
}

func (x *Entity) DBSelectAllWhereAll(fieldsToMatch []string) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN +
		" WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? AND ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.Query(x.GetFieldsValues(fieldsToMatch)...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func (x *Entity) DBSelectAllWhereAllContext(ctx context.Context, fieldsToMatch []string) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN +
		" WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? AND ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, x.GetFieldsValues(fieldsToMatch)...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func (x *Entity) DBSelectAllWhereAny(fieldsToMatch []string) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN +
		" WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? OR ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.Query(x.GetFieldsValues(fieldsToMatch)...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func (x *Entity) DBSelectAllWhereAnyContext(ctx context.Context, fieldsToMatch []string) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN +
		" WHERE " + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? OR ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, x.GetFieldsValues(fieldsToMatch)...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func (x *Entity) DBExists(fields []string) (bool, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") +
		" FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fields), " = ? AND ") + " = ? LIMIT 1"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return false, err
	}
	rows, err := stmt.Query(x.GetFieldsValues(fields)...)
	if err != nil {
		return false, err
	}
	defer rows.Close()
	results, err := readRows(Fields, rows)
	if err != nil {
		return false, err
	}
	if len(results) == 0 {
		return false, nil
	}
	*x = *results[0]
	return true, nil
}

func (x *Entity) DBExistsContext(ctx context.Context, fields []string) (bool, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") +
		" FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fields), " = ? AND ") + " = ? LIMIT 1"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return false, err
	}
	rows, err := stmt.QueryContext(ctx, x.GetFieldsValues(fields)...)
	if err != nil {
		return false, err
	}
	defer rows.Close()
	results, err := readRows(Fields, rows)
	if err != nil {
		return false, err
	}
	if len(results) == 0 {
		return false, nil
	}
	*x = *results[0]
	return true, nil
}

func (x *Entity) DBCountWhereAll(fields []string) (int, error) {
	query := "SELECT COUNT(*) FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fields), " = ? AND ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return 0, err
	}
	var count int
	err = stmt.QueryRow(x.GetFieldsValues(fields)...).Scan(&count)
	return count, err
}

func (x *Entity) DBCountWhereAllContext(ctx context.Context, fields []string) (int, error) {
	query := "SELECT COUNT(*) FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fields), " = ? AND ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return 0, err
	}
	var count int
	err = stmt.QueryRowContext(ctx, x.GetFieldsValues(fields)...).Scan(&count)
	return count, err
}

func (x *Entity) DBCountWhereAny(fields []string) (int, error) {
	query := "SELECT COUNT(*) FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fields), " = ? OR ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return 0, err
	}
	var count int
	err = stmt.QueryRow(x.GetFieldsValues(fields)...).Scan(&count)
	return count, err
}

func (x *Entity) DBCountWhereAnyContext(ctx context.Context, fields []string) (int, error) {
	query := "SELECT COUNT(*) FROM " + FQTN + " WHERE " + strings.Join(GetQualifiedFields(fields), " = ? OR ") + " = ?"
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return 0, err
	}
	var count int
	err = stmt.QueryRowContext(ctx, x.GetFieldsValues(fields)...).Scan(&count)
	return count, err
}

func (x *Entity) DBFindOrCreate(fields []string) error {
	exists, err := x.DBExists(fields)
	if err != nil {
		return err
	}
	if exists {
		return nil
	}
	_, err = x.DBInsert(fields)
	if err != nil {
		return err
	}
	_, err = x.DBExists(fields)
	if err != nil {
		return err
	}
	return nil
}

func (x *Entity) DBFindOrCreateContext(ctx context.Context, fields []string) error {
	exists, err := x.DBExistsContext(ctx, fields)
	if err != nil {
		return err
	}
	if exists {
		return nil
	}
	_, err = x.DBInsertContext(ctx, fields)
	if err != nil {
		return err
	}
	_, err = x.DBExistsContext(ctx, fields)
	if err != nil {
		return err
	}
	return nil
}

func (x *Entity) DBSubquerySelectAllWhereAll(fieldsToMatch []string, subquery string, args ...any) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN +
		" WHERE (" + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? AND ") + " = ?) " + subquery
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	allArgs := append(x.GetFieldsValues(fieldsToMatch), args...)
	rows, err := stmt.Query(allArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func (x *Entity) DBSubquerySelectAllWhereAllContext(ctx context.Context, fieldsToMatch []string, subquery string, args ...any) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN +
		" WHERE (" + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? AND ") + " = ?) " + subquery
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	allArgs := append(x.GetFieldsValues(fieldsToMatch), args...)
	rows, err := stmt.QueryContext(ctx, allArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func (x *Entity) DBSubquerySelectAllWhereAny(fieldsToMatch []string, subquery string, args ...any) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN +
		" WHERE (" + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? OR ") + " = ?) " + subquery
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	allArgs := append(x.GetFieldsValues(fieldsToMatch), args...)
	rows, err := stmt.Query(allArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}

func (x *Entity) DBSubquerySelectAllWhereAnyContext(ctx context.Context, fieldsToMatch []string, subquery string, args ...any) ([]*Entity, error) {
	query := "SELECT " + strings.Join(GetQualifiedFields(Fields), ", ") + " FROM " + FQTN +
		" WHERE (" + strings.Join(GetQualifiedFields(fieldsToMatch), " = ? OR ") + " = ?) " + subquery
	stmt, err := getPreparedStmt(query)
	if err != nil {
		return nil, err
	}
	allArgs := append(x.GetFieldsValues(fieldsToMatch), args...)
	rows, err := stmt.QueryContext(ctx, allArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return readRows(Fields, rows)
}
